version: '3'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: chupinohosting
    networks:
      - backend

  app:
    build: .
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_NAME: chupinohosting
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - backend
    command: sh -c "chmod +x init-app.sh && ./init-app.sh"

networks:
  backend:
    driver: bridge